version: 2
# https://circleci.com/docs/configuration#machine
jobs:
    # @todo, separate build and test phases.
    build:
        docker:
            - image: drupaldocker/php:7.0-cli
        working_directory: ~/terminus_build_tools_plugin
        environment:
            BASH_ENV: ~/.bashrc
            TZ: "/usr/share/zoneinfo/America/Los_Angeles"
            TERMINUS_ORG: CI for Drupal 8 + Composer
            GITHUB_USERNAME: pantheon-ci-bot
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "composer.lock" }}
            - run:
                name: dependencies
                command: |
                  gem install circle-cli
                  composer global require -n "hirak/prestissimo:^0.3"
                  mkdir -p $HOME/terminus
                  /usr/bin/env COMPOSER_BIN_DIR=$HOME/bin composer --working-dir=$HOME/terminus require "pantheon-systems/terminus:dev-master"
                  composer --working-dir=$HOME/terminus config minimum-stability dev
                  terminus --version
    # Install the copy of the Build Tools Plugin cloned by CircleCI as a plugin
    # in Terminus, so that all build-env commands run the System-Under-Test.
                  mkdir -p $HOME/.terminus/plugins
                  ln -s $(pwd) $HOME/.terminus/plugins
                  terminus list -n build
            - save_cache:
                key: dependency-cache-{{ checksum "composer.lock" }}
                paths:
                  - ~/.composer/cache
            - run:
                name: git config
                command: |

                  git config --global user.email "$GIT_EMAIL"
                  git config --global user.name "Circle CI"
